### ISSUE TITLE
Can't follow from Pleroma

### ISSUE THREAD

**Issue by mcg** [pfefferle/wordpress-activitypub#19] opened 2019-01-18 20:53 UTC
Is this a known issue or something with my WordPress setup? I am able to follow from Mastodon, but my personal Pleroma instance returns a 500. Webfinger for my WP is https://client.webfinger.net/lookup?resource=mcg%40blog.braintube.com

**Comment by mcg** [comment] 2019-02-10 20:16
Same issue with version 0.3.2

**Comment by pfefferle** [comment] 2019-02-19 21:55
Thanks for filing the issue: https://git.pleroma.social/pleroma/pleroma/issues/649#note_17071

**Comment by DeadSuperHero** [comment] 2019-02-20 18:43
Seems like it might be related to this problem, @pfefferle ? https://git.pleroma.social/pleroma/pleroma/issues/364

**Comment by pfefferle** [comment] 2019-02-21 08:36
@DeadSuperHero yes, thanks for the reference!

Seems to be fixed with this commit: https://git.pleroma.social/pleroma/pleroma/commit/2813f28b6fa1618efb01f4bd570e055ca16efbc5

**Comment by mcg** [comment] 2019-02-25 02:00
Some updates related to similar issues with Pleroma and Pixelfed. Perhaps something similar is happening here? https://pleroma.site/objects/de0b6f01-d63f-4bc8-8477-a56f3369853b

**Comment by mcg** [comment] 2019-03-11 21:55
I've updated to 0.6.0 which I assume has this fix included. Still unable to follow.

**Comment by pfefferle** [comment] 2019-03-12 06:38
can you send me your identifier, that I could test it?

**Comment by mcg** [comment] 2019-03-12 13:46
@pfefferle Same as the OP of this issue, https://client.webfinger.net/lookup?resource=mcg%40blog.braintube.com 

Does that work?

**Comment by pfefferle** [comment] 2019-03-12 14:38
Sorry, I read that on the phone... can you send me the instance you tried it on? It might be a version problem. I tested some instances and it worked only on some of them...

**Comment by mcg** [comment] 2019-03-12 18:01
Oh... It's my single user personal instance, running an up to date(as of a couple of days) Pleroma dev. Can you tell me where you've had this work?

**Comment by pfefferle** [comment] 2019-03-12 18:03
Let‘s try it the other way ‚round... can you try to follow `pfefferle@notiz.blog`?

**Comment by mcg** [comment] 2019-03-12 18:14
That works. Huh... The avatar and user data doesn't even load for my WP, does for yours. Looks like this:
![(20) social braintube com 2019-03-12 14-12-40](https://user-images.githubusercontent.com/305/54225016-23bdb680-44d1-11e9-8c0b-d0ce063a3216.jpg)

**Comment by pfefferle** [comment] 2019-03-12 21:10
If it is your instance, can you find any valuable log entries...? I can reproduce it with another website of mine, but I have no clue what the problem might be...

**Comment by pfefferle** [comment] 2019-03-12 21:23
found the problem... can you retest with version 0.7.0?

**Comment by mcg** [comment] 2019-03-13 01:15
Progress with 0.7.0. Searching for my account, it now shows the correct avatar etc... but follows still fail. 

Web logs during a search.
```
- - [12/Mar/2019:20:48:47 -0400] "GET /.well-known/host-meta HTTP/1.1" 404 54288 "-" "hackney/1.14.3"
 - - [12/Mar/2019:20:48:47 -0400] "GET /.well-known/host-meta HTTP/1.1" 404 54288 "-" "hackney/1.14.3"
 - - [12/Mar/2019:20:48:47 -0400] "GET /.well-known/webfinger?resource=acct:mcg@blog.braintube.com HTTP/1.1" 200 338 "
-" "hackney/1.14.3"
 - - [12/Mar/2019:20:48:47 -0400] "GET /author/mcg/ HTTP/1.1" 200 2480 "-" "hackney/1.14.3"
```

I don't see any new requests when I attempt to follow. No errors on Pleroma when I try to follow, just doesn't complete.

**Comment by pfefferle** [comment] 2019-03-13 07:49
Hmm, works fine on pleroma.site

![Bildschirmfoto 2019-03-13 um 08 47 43](https://user-images.githubusercontent.com/2373/54261755-df7ff400-456c-11e9-89f0-abcabeed4a95.png)

**Comment by mcg** [comment] 2019-03-13 13:34
I ended up needing to remove a bunch of stale follow requests from the DB and following worked! However posts don't seem to be making it across. Progress at least.

**Comment by pfefferle** [comment] 2019-03-13 16:56
You are right! It sends no activities!

I love working with STANDARDS!!!

**Comment by pfefferle** [comment] 2019-03-14 16:48
Can you load the profile of your blog on pleroma and check if the posts will show up there? I found that posts are visible on the profile pages but not in the timelines.

**Comment by mcg** [comment] 2019-03-14 17:03
That appears to be happening. I can see posts on the profile but not in the timeline. Couple of additional things. They don't get pushed to AP until the WP cron runs, I didn't expect that. Also, for the tests posts I was trying, I didn't see them in Pleroma, then I deleted them on WP. When the WP cron eventually ran, it was publishing deleted/trashed posts. Probably shouldn't do that.

**Comment by pfefferle** [comment] 2019-03-14 17:19
OK, found the posting issue... It was a problem with sharedInboxes... I will test new features always on pleroma... they take the spec more serious then mastodon. Will publish an update.

Regarding the cron: I had to do it like that, because with a huge list of followers, saving a post would take way too long and may run into a timeout!

Regarding the publishing/deleted/trashed thing: I will check if a post is still published before sending it. Good point.

**Comment by pfefferle** [comment] 2019-03-14 17:20
@mcg thanks for debugging btw :)

**Comment by pfefferle** [comment] 2019-03-14 22:13
Finally finally finally https://github.com/pfefferle/wordpress-activitypub/releases/tag/0.7.1

But I do not dare to close the ticket yet ;)

**Comment by mcg** [comment] 2019-03-14 22:47
Looks like this one fixes it. I can see posts in my timeline and deleted posts aren’t published. 👍

**Comment by pfefferle** [comment] 2019-03-15 09:56
❤️

**Closed by pfefferle** 2019-03-15 09:56 UTC
Labels: bug

**Comment by jdormit** [comment] 2019-03-15 10:27
@pfefferle what did the issue with sharedInbox end up being? I have follows working from Pleroma to Pterotype, but Pleroma keeps 500ing whenever I send it an Activity...

**Comment by pfefferle** [comment] 2019-03-15 10:29
It was not really an issue because Pleroma accepted the Post. The issue was, that I used the shared inbox, but haven't added the `to` and `cc` fields, so Pleroma added the post only to the global stream and not to the streams of the followers.

**Comment by pfefferle** [comment] 2019-03-15 10:32
@jdormit before I had an issue, because Pleroma requires an `ID` for every activity.

**Comment by DeadSuperHero** [comment] 2019-12-26 04:43
Hey, I wanted to follow up on this. I'm a Pleroma user, and recently started using this plugin with my Wordpress installation site.

I'm able to see the actor dsh_blog@deadsuperhero.com from the Pleroma side, but no posts appear to be fetched. I tried sending a follow request, but it didn't appear to get sent over to my blog.

I actually wasn't able to discovery my blog's actor until a recent update of Pleroma. I'll try upgrading again to see whether that helps any, but I wanted to inform you that as of right now, this does seem to affect Pleroma installations.
