### ISSUE TITLE
Possibility to follow complete blog, and not only author

### ISSUE THREAD

**Issue by svenhardwarepunk** [pfefferle/wordpress-activitypub#177] opened 2022-11-13 11:10 UTC
Hi, 

do you see the possibility to implement, that I can follow the complete blog, and not only by author? We have a blog for a community with different authors, and also new authors from time to time, and it would be great, if I can get all news from the blog. 
Thanks for this plugin, I love it!

Greetings

Sven

**Comment by pfefferle** [comment] 2022-11-23 16:24
duplicate of #1

**Closed by pfefferle** 2022-11-23 16:24 UTC
